// <auto-generated />
namespace mls.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class cqstatusadded20190805 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cqstatusadded20190805));
        
        string IMigrationMetadata.Id
        {
            get { return "201908051929205_cqstatusadded20190805"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
