// <auto-generated />
namespace mls.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class poplan20190802 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(poplan20190802));
        
        string IMigrationMetadata.Id
        {
            get { return "201908030015428_poplan20190802"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
