// <auto-generated />
namespace mls.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class productionstockout20190308 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(productionstockout20190308));
        
        string IMigrationMetadata.Id
        {
            get { return "201903081155106_productionstockout20190308"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
