// <auto-generated />
namespace mls.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class reqchanges20190919 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(reqchanges20190919));
        
        string IMigrationMetadata.Id
        {
            get { return "201909191040294_reqchanges20190919"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
