// <auto-generated />
namespace mls.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class cqupdate20190808 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cqupdate20190808));
        
        string IMigrationMetadata.Id
        {
            get { return "201908090327071_cqupdate20190808"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
