// <auto-generated />
namespace mls.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ncrcost20190130 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ncrcost20190130));
        
        string IMigrationMetadata.Id
        {
            get { return "201901310455412_ncrcost20190130"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
