// <auto-generated />
namespace mls.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addshiphot20191013 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addshiphot20191013));
        
        string IMigrationMetadata.Id
        {
            get { return "201910131526276_addshiphot20191013"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
