// <auto-generated />
namespace mls.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updateinvtransfer20200818 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateinvtransfer20200818));
        
        string IMigrationMetadata.Id
        {
            get { return "202008190126588_updateinvtransfer20200818"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
